const ORDER_NEW = "NEW"
const ORDER_ACCEPTED = "ACCEPTED"
const ORDER_REJECTED = "REJECTED"
const ORDER_IN_PROGRESS = "IN_PROGRESS"
const ORDER_COMPLETED = "COMPLETED"
const ORDER_DELIVERED = "DELIVERED"

export {
  ORDER_NEW,
  ORDER_ACCEPTED,
  ORDER_REJECTED,
  ORDER_IN_PROGRESS,
  ORDER_COMPLETED,
  ORDER_DELIVERED
}